### ISSUE TITLE
on the mobile: when the focus is on the text input in ex1&4 the instructions are not visible anymore

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#123]
this is because the focus on the input triggers the keyboard to show up and scrolls a bit the content. 

this was a problem before, but it's worse now when the exercise starts with the focus on the text input. 

before one could at least read the instructions before giving the focus to the text input and the scroll hapening. now, from the very begining the screen looks like this, on a huawei p9, with a quite large screen actually: 

![screenshot_20171222-122500](https://user-images.githubusercontent.com/464519/34297217-1b99bb8e-e717-11e7-82eb-864481dbecb3.png)

the options that i see are: 
- having the focus on the hint, and making sure that the text input is the next in line. this way, to start typing one has to "only tab" before writing
- have the text input have the focus but only when not on the mobile
- redesign exercises 1&4 such that the entire content is visible within the top 50% of the page. this could include decreasing the font of the text, and reducing the padding around the text

**Comment by sibrenvanvliet** [comment]
My preference is giving focus to the text input only when not on mobile. When you are using the program on a computer, it is nice if you can keep your hands on the keyboard as much as possible, because moving your hand to the mouse takes some time. On mobile, your fingers are always on the screen, so you can tap the textbox to give it focus, and your fingers will be over the area where the keyboard then appears.

**Comment by mircealungu** [comment]
I totally agree with you that ti's nice to not use the mouse. 
Note that the solution with the focus on the previous element, means that you can simply Tab and then start typing. 
However, I like the solution with focus when not on mobile too. I just don't know how easy and reliable is "detecting that you're on mobile". If both easy and realiable, then I'll be happy to go with that solution. Otherwise, given that we the keyboard-first people might actually be a minority of users, we could go with the other solution which is probably the simplest for now.

**Comment by sibrenvanvliet** [comment]
After some research, it seems that reliable mobile detection is not easy. One way is to detect whether a mobile browser is being used, by reading the user agent. [StackOverflow considers this bad practice](https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser) because user agent strings go out of date, yet [this website](http://detectmobilebrowsers.com/) uses a regex from 2014 but still correctly detects the browser type on all browsers on all the devices I could find in my house :)

Another approach is, like responsive UIs, using the screen resolution to determine this. However, you mention that you use a Huawei P9, which has a Full HD resolution, but the keyboard still covers the question description. My laptop has a significantly smaller screen resolution, so this does not appear to be a valid approach.

Since our goal is to make sure that the question prompt is on screen, another possible way is checking whether this element is inside the browser viewport. So, if the keyboard on a phone shows up, but this causes the prompt to be outside the viewport, this should be detected and the keyboard must be collapsed again, by removing focus from the text field. [This page shows how to check whether an element is in the viewport.](https://medium.com/talk-like/detecting-if-an-element-is-in-the-viewport-jquery-a6a4405a3ea2) However, since this would cause the keyboard to pop up on the screen and then automatically disappear again, I can imagine this being confusing or annoying to the user.

So now, the question is which approach we go for. My choice would be comparing the user agent to a regex. Even though it is a discouraged method, a four year old example still works fine for all major browsers I tested. If we want to steer clear from such a hacky approach, however, I think it is best to disable auto-focus on all devices. Then we know for sure that mobile users will see the question prompt correctly. Desktop users will most likely use the mouse for some exercises anyway (like matching three pairs, or clicking words in the text) so an extra mouse click is likely not a large setback.

Yet another possible approach: Since we will be making a settings panel for #115, we can make "Auto-focus on text fields" a checkbox option.

**Comment by mircealungu** [comment]
Nice analysis Sibren. 

One problem: 

Another approach is, like responsive UIs, using the screen resolution to determine this. However, you mention that you use a Huawei P9, which has a Full HD resolution, but the keyboard still covers the question description. My laptop has a significantly smaller screen resolution, so this does not appear to be a valid approach. I think if you take in consideration also the density of points per inch not only the resolution, you should still be able to distinguish any mobile from any desktop.

however, there seem to be multiple solutions
that use regexes. so let's go with that. 

if you encapsulate it nicely in a stand along function,
we can redefine it in the future when a better detection
method appears.
